### ISSUE TITLE
Certain texture png's automatically turn new png to grayscale

### ISSUE THREAD

**Issue by Patrick12115** [HarbourMasters64/retro#23]
The example I did was Link's tunic. When trying to change the texture with something that had different colors on it, it would just make it all gray scale in game. I'm not sure if this is the right place for this issue, but I figured with it so new, I'd start here. I will attach the OTR with the mentioned texture replacement in the zip folder below, along with the screenshot on this post.

![image](https://user-images.githubusercontent.com/115201185/207527916-a3168804-7887-4d85-967e-b653c1de19e8.png)
[TunicColorTest.zip](https://github.com/HarbourMasters/retro/files/10225161/TunicColorTest.zip)

**Comment by leggettc18** [comment]
So this is just what the game is programmed to do with the Tunic texture at the moment. It grayscales it and applies the corresponding color for which tunic you have equipped. Having SoH be able to override that behavior is probably something that will happen eventually, but I have no idea what form that will take right now.

**Comment by Patrick12115** [comment]
Yeah, I didn't figure this would be anything too soon. Proxy just said that we would definitely eventually want to work that out, so I made an issue about it to just track it, essentially.

**Comment by leggettc18** [comment]
Oh, right, apologies for the misunderstanding.

**Comment by Patrick12115** [comment]
You're fine, I wasn't even sure if this was the right place to create the issue, but I figured it'd just get lost in the Shipwright GitHub.
