### ISSUE TITLE
Certian textures ripped are broken. 

### ISSUE THREAD

**Issue by numbypad** [HarbourMasters64/retro#27]
Some textures dumped by the tool are black and white and static. For example I was replacing all the Gerudo symbols in the game with the 1.0 textures I dumped from my cartridge, the symbol on the stair case at the entrance of spirit temple didn't have a properly dumped texture. It was black and white and unrecognizable, even when I managed to trace it down, replacing it resulted in a messed up texture in game.  there are a few more examples of this as well.

**Comment by numbypad** [comment]
the one I mentioned in my example of the staircase pillar is called jyasinzou_room_0Tex_00B928.png and if I replace it with the 1.0 texture you can at least make out that the crescent moon is there but it's messy I'll include a picture of the 1.0 texture I ripped, the texture retro is dumping from soh, and a picture of it in game. I'm on the latest release. 
![jyasinzou_room_0Tex_00B928](https://user-images.githubusercontent.com/89367228/212601737-efb856e0-6488-4112-97d5-e1784fb73594.png)
![1jyasinzou_room_0Tex_00B928](https://user-images.githubusercontent.com/89367228/212601754-af02cc9a-fa69-43d8-bb60-6989830f7e08.png)
![Capture](https://user-images.githubusercontent.com/89367228/212601877-707a04d5-fbe9-4c94-90b8-431027ad8b62.PNG)

**Comment by KiritoDv** [comment]
This texture is a palette, thats why it looks like that, right now its unsupported to load regular textures, im closing this issue
